// import storage from "../assets/img/5x10-storage-unit-min-scaled-e1620915610988.jpg"
import NavLogo from "../assets/img/d group(2)logo.jpg"
import Home_Slider1 from "../assets/img/slider_image_1.jpg"
import Home_Slider2 from "../assets/img/slider_image_2.jpg"
import Home_Slider3 from "../assets/img/slider_image_3.jpg"
import Home_Slider4 from "../assets/img/slider_image_4.jpg"
import Home_Slider5 from "../assets/img/slider_image_5.jpg"
import Card1 from "../assets/img/car carrier 2.jpeg"
import Card2 from "../assets/img/card2.jpeg"
import Card4 from "../assets/img/card4.jpeg"
import Chooes from "../assets/img/chooes.jpeg"
import Logomain from "../assets/img/logomain.png"
import ContactUS from "../assets/img/contact.jpeg"
import AboutUs from "../assets/img/About.jpeg"
import Service from "../assets/img/chooes.jpeg"
import storage from "../assets/img/storage.jpg"
import transection from "../assets/img/transection1.jpeg"
import transport from "../assets/img/transport.jpeg"
import card3 from "../assets/img/card3.jpeg"
import card2 from "../assets/img/card2.jpeg"
import Vishal from "../assets/img/vishal.jpg"
import Shital from "../assets/img/Shital.jpg"
import Harish from "../assets/img/Harish.jpg"
import Sukhwinder from "../assets/img/Sukhwinder.jpg"
import Gourish from "../assets/img/Gourish.jpg"
import Mohit from "../assets/img/Mohit.jpg"
import Harshal from "../assets/img/Harshal.jpg"
import Dilip from "../assets/img/Dilip.jpg"
import Kalpesh from "../assets/img/Kalpesh.jpg"



export  {
    Vishal,Kalpesh,Dilip,Harshal,Mohit,Gourish,Sukhwinder,Harish,Shital,storage,transection,card2,card3,transport,NavLogo,Home_Slider1,Home_Slider2,Home_Slider3,Home_Slider4,Home_Slider5,Card1,Card2,Card4,Chooes,Logomain,ContactUS,AboutUs,Service
}
